### ISSUE TITLE
Using the plugin with Kotlin and GitHub Actions

### ISSUE THREAD

**Issue by PHPirates** [nbaztec/coveralls-jacoco-gradle-plugin#6]
Hi, thanks a lot for creating this!

I'm still seeing no updates on my coveralls though: https://coveralls.io/github/PHPirates/kotlin-template-project

This is what I did:

* Added the plugin to my build file: https://github.com/PHPirates/kotlin-template-project/blob/master/build.gradle.kts
* Add `COVERALLS_REPO_TOKEN` secret to my repository.
* Use the following GitHub Actions yml: https://github.com/PHPirates/kotlin-template-project/blob/master/.github/workflows/main.yml which basically sets the token and runs `./gradlew check jacocoTestReport coverallsJacoco`

Codecov does get coverage reported correctly.
I also tried to run the coverallsJacoco task locally, with the environment variable set, but I also didn't see updates on Coveralls.

Any idea how to debug this?

**Comment by nbaztec** [comment]
Seems the directory [here](https://github.com/PHPirates/kotlin-template-project/tree/master/src/main/kotlin/nl.deltadak.ktemplate) is  `nl.deltadak.ktemplate` instead of `nl/deltadak/ktemplate`. 
While Kotlin supports arbitrary directory names, it's recommended to flatten just the commonroot package and the rest should follow the normal java styled directory structure.

So in your case, renaming the directory containing the kotlin files would fix it. Or you can alternatively omit the directory all together, throw all files on `src/main/kotlin`, specify the rootPackage in plugin configuration and it should just work.

**Comment by PHPirates** [comment]
Thanks! Since it shows the same in IntelliJ, I had not noticed the mistake. It works now, great!
